sudo: required

language: java

jdk:
- oraclejdk8

services:
- docker

script: 
- mvn -q clean package docker:build

after_success:
- docker images
- docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
- docker push sentinel01/springboot-hello-docker:latest
